# Generated by Django 3.0.4 on 2020-03-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contractors',
            new_name='Contractor',
        ),
    ]
